"""empty message

Revision ID: 09de5c85b5c8
Revises: 2180ed1f4b12
Create Date: 2023-07-18 13:21:57.493164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09de5c85b5c8'
down_revision = '2180ed1f4b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edition_format', sa.String(length=40), nullable=False))

    with op.batch_alter_table('Ebay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edition_format', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ebay', schema=None) as batch_op:
        batch_op.drop_column('edition_format')

    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.drop_column('edition_format')

    # ### end Alembic commands ###
