"""empty message

Revision ID: 1fb487b50ee5
Revises: 5790fddcea28
Create Date: 2023-08-05 12:56:24.081870

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '1fb487b50ee5'
down_revision = '5790fddcea28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=app.DateTimeNumeric(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=app.DateTimeNumeric(),
               type_=sa.DECIMAL(precision=5, scale=2),
               nullable=False)

    # ### end Alembic commands ###
