"""empty message

Revision ID: 375d01c12d8c
Revises: 305d5f92f550
Create Date: 2023-08-02 21:30:59.263984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375d01c12d8c'
down_revision = '305d5f92f550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ebay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historical_new_total_price', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('historical_used_total_price', sa.Numeric(precision=5, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ebay', schema=None) as batch_op:
        batch_op.drop_column('historical_used_total_price')
        batch_op.drop_column('historical_new_total_price')

    # ### end Alembic commands ###
