"""empty message

Revision ID: 37cb22d5e977
Revises: a69c1a865677
Create Date: 2023-08-05 21:07:58.476490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_utils import CompositeType
from app import db

# revision identifiers, used by Alembic.
revision = '37cb22d5e977'
down_revision = 'a69c1a865677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=postgresql.ARRAY(CompositeType('composite_type', [db.Column('my_datetime_column', db.DateTime(), table=None), db.Column('my_numeric_column', db.Numeric(precision=5, scale=2), table=None)]), dimensions=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=postgresql.ARRAY(CompositeType('composite_type', [db.Column('my_datetime_column', db.DateTime()), db.Column('my_numeric_column', db.Numeric(precision=5, scale=2))]), dimensions=1),
               type_=sa.DECIMAL(precision=5, scale=2),
               nullable=False)

    # ### end Alembic commands ###
