"""empty message

Revision ID: 3def91cbda6f
Revises: 010b875d3d62
Create Date: 2023-08-05 12:27:41.546031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3def91cbda6f'
down_revision = '010b875d3d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=app.DateTimeNumeric(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=app.DateTimeNumeric(),
               type_=sa.DECIMAL(precision=5, scale=2),
               nullable=False)

    # ### end Alembic commands ###
