"""empty message

Revision ID: 5790fddcea28
Revises: 3def91cbda6f
Create Date: 2023-08-05 12:56:06.283731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5790fddcea28'
down_revision = '3def91cbda6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Amazon')
    op.drop_table('Ebay')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ebay',
    sa.Column('book_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('ebay_link', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('isbn', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('edition_format', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('new_product_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('new_delivery_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('new_total_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('used_product_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('used_delivery_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('used_total_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('historical_new_total_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('historical_used_total_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('isbn', name='Ebay_pkey'),
    comment='Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.'
    )
    op.create_table('Amazon',
    sa.Column('book_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('amazon_link', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('isbn', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('edition_format', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('new_product_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('new_delivery_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('new_total_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('used_product_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('used_delivery_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('used_total_price', sa.DECIMAL(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('isbn', name='Amazon_pkey'),
    comment='Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.'
    )
    # ### end Alembic commands ###
