"""empty message

Revision ID: 6447e96d797e
Revises: 68f439e304f1
Create Date: 2023-08-05 21:43:05.227531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_utils import CompositeType
from app import db

# revision identifiers, used by Alembic.
revision = '6447e96d797e'
down_revision = '68f439e304f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Amazon',
    sa.Column('book_name', sa.String(length=200), nullable=False),
    sa.Column('amazon_link', sa.String(length=200), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('edition_format', sa.String(length=40), nullable=False),
    sa.Column('new_product_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('new_delivery_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('new_total_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used_product_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used_delivery_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used_total_price', postgresql.ARRAY(CompositeType('composite_type', [db.Column('my_datetime_column', db.TIMESTAMP()), db.Column('my_numeric_column', db.Numeric(precision=5, scale=2))]), dimensions=1), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Amazon')
    # ### end Alembic commands ###
