"""empty message

Revision ID: 66445e5efb8b
Revises: 37cb22d5e977
Create Date: 2023-08-05 21:23:56.614991

"""
from alembic import op
import sqlalchemy as sa
from app import db
from sqlalchemy.dialects import postgresql
from sqlalchemy_utils import CompositeType

# revision identifiers, used by Alembic.
revision = '66445e5efb8b'
down_revision = '37cb22d5e977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=postgresql.ARRAY(CompositeType('composite_type', [db.Column('my_datetime_column', db.DateTime(), table=None), db.Column('my_numeric_column', db.Numeric(precision=5, scale=2), table=None)]), dimensions=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=postgresql.ARRAY(CompositeType('composite_type', [db.Column('my_datetime_column', db.DateTime(), table=None), db.Column('my_numeric_column', db.Numeric(precision=5, scale=2), table=None)]), dimensions=1),
               type_=sa.DECIMAL(precision=5, scale=2),
               nullable=False)

    # ### end Alembic commands ###
