"""empty message

Revision ID: 68f439e304f1
Revises: 66445e5efb8b
Create Date: 2023-08-05 21:36:12.054184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_utils import CompositeType
from app import db

# revision identifiers, used by Alembic.
revision = '68f439e304f1'
down_revision = '66445e5efb8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=postgresql.ARRAY(CompositeType('composite_type', [db.Column('my_datetime_column', db.TIMESTAMP()), db.Column('my_numeric_column', db.Numeric(precision=5, scale=2))]), dimensions=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=postgresql.ARRAY(CompositeType('composite_type', [db.Column(db.TIMESTAMP()), db.Column(db.Numeric(precision=5, scale=2))]), dimensions=1),
               type_=sa.DECIMAL(precision=5, scale=2),
               nullable=False)

    # ### end Alembic commands ###
