"""empty message

Revision ID: 78470cf315c4
Revises: 2936cff94a4f
Create Date: 2023-08-24 15:53:01.936609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78470cf315c4'
down_revision = '2936cff94a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Ebay', ['isbn'], ['isbn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
