"""empty message

Revision ID: 78c1a000d3cd
Revises: fbb6a57168f5
Create Date: 2023-07-15 20:19:54.244655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c1a000d3cd'
down_revision = 'fbb6a57168f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ebay', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=13),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Ebay_isbn_seq"\'::regclass)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ebay', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(length=13),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Ebay_isbn_seq"\'::regclass)'))

    # ### end Alembic commands ###
