"""empty message

Revision ID: a69c1a865677
Revises: 1fb487b50ee5
Create Date: 2023-08-05 21:06:28.085074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a69c1a865677'
down_revision = '1fb487b50ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=postgresql.ARRAY(CompositeType('composite_type', [Column('currency', DateTime(), table=None), Column('amount', Numeric(precision=5, scale=2), table=None)]), dimensions=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=postgresql.ARRAY(CompositeType('composite_type', [Column('currency', DateTime(), table=None), Column('amount', Numeric(precision=5, scale=2), table=None)]), dimensions=1),
               type_=sa.DECIMAL(precision=5, scale=2),
               nullable=False)

    # ### end Alembic commands ###
