"""empty message

Revision ID: b7374bd8a7c2
Revises: 
Create Date: 2023-07-15 19:27:48.439846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7374bd8a7c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Amazon',
    sa.Column('book_name', sa.String(length=200), nullable=False),
    sa.Column('amazon_link', sa.String(length=200), nullable=False),
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('product_price', sa.Numeric(precision=2), nullable=False),
    sa.Column('delivery_price', sa.Numeric(precision=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('Ebay',
    sa.Column('book_name', sa.String(length=200), nullable=False),
    sa.Column('ebay_link', sa.String(length=200), nullable=False),
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('product_price', sa.Numeric(precision=2), nullable=False),
    sa.Column('delivery_price', sa.Numeric(precision=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ebay')
    op.drop_table('Amazon')
    # ### end Alembic commands ###
