"""empty message

Revision ID: da37195d7915
Revises: 88068e23b474
Create Date: 2023-07-21 11:07:55.523321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da37195d7915'
down_revision = '88068e23b474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ebay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_product_price', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('new_delivery_price', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('new_total_price', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('used_product_price', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('used_delivery_price', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('used_total_price', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.drop_column('total_price')
        batch_op.drop_column('delivery_price')
        batch_op.drop_column('product_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ebay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_price', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('delivery_price', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('used_total_price')
        batch_op.drop_column('used_delivery_price')
        batch_op.drop_column('used_product_price')
        batch_op.drop_column('new_total_price')
        batch_op.drop_column('new_delivery_price')
        batch_op.drop_column('new_product_price')

    # ### end Alembic commands ###
