"""empty message

Revision ID: e3b06634ab95
Revises: 2a888f7484ff
Create Date: 2023-08-07 17:15:30.186226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b06634ab95'
down_revision = '2a888f7484ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Amazon',
    sa.Column('book_name', sa.String(length=200), nullable=False),
    sa.Column('amazon_link', sa.String(length=200), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('edition_format', sa.String(length=40), nullable=False),
    sa.Column('new_product_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('new_delivery_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('new_total_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used_product_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used_delivery_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used_total_price', sa.ARRAY(sa.Numeric(precision=5, scale=2)), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Amazon')
    # ### end Alembic commands ###
