"""empty message

Revision ID: e5c0d73bd9e6
Revises: f0269b84dde4
Create Date: 2023-08-07 15:53:05.802000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c0d73bd9e6'
down_revision = 'f0269b84dde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Amazon',
    sa.Column('book_name', sa.String(length=200), nullable=False),
    sa.Column('amazon_link', sa.String(length=200), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('edition_format', sa.String(length=40), nullable=False),
    sa.Column('new_product_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('new_delivery_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('new_total_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used_product_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used_delivery_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used_total_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Amazon')
    # ### end Alembic commands ###
