"""empty message

Revision ID: f0269b84dde4
Revises: 6447e96d797e
Create Date: 2023-08-07 15:52:17.846067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0269b84dde4'
down_revision = '6447e96d797e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=sa.NullType(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amazon', schema=None) as batch_op:
        batch_op.alter_column('used_total_price',
               existing_type=sa.NullType(),
               nullable=True)

    # ### end Alembic commands ###
